function histogram_data(VertexNormals1, YData1, XData1, Vertices1, Faces1, FaceVertexCData1, CData1)
%CREATEFIGURE(VERTEXNORMALS1, YDATA1, XDATA1, VERTICES1, FACES1, FACEVERTEXCDATA1, CDATA1)
%  VERTEXNORMALS1:  patch vertexnormals
%  YDATA1:  patch ydata
%  XDATA1:  patch xdata
%  VERTICES1:  patch vertices
%  FACES1:  patch faces
%  FACEVERTEXCDATA1:  patch facevertexcdata
%  CDATA1:  patch cdata

%  Auto-generated by MATLAB on 23-Apr-2015 16:41:16

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on','FontWeight','bold',...
    'FontSize',24,...
    'CLim',[1 2]);
box(axes1,'on');

% Create patch
patch('Parent',axes1,'VertexNormals',VertexNormals1,'YData',YData1,...
    'XData',XData1,...
    'Vertices',Vertices1,...
    'Faces',Faces1,...
    'FaceColor','flat',...
    'FaceVertexCData',FaceVertexCData1,...
    'DisplayName','sumA',...
    'CData',CData1);

% Create title
title('Reuters: Number of documents over its length','Interpreter','latex',...
    'FontWeight','bold',...
    'FontSize',40);

% Create xlabel
xlabel('Number of words','Interpreter','latex','FontWeight','bold',...
    'FontSize',30);

% Create ylabel
ylabel('Number of documents','Interpreter','latex','FontWeight','bold',...
    'FontSize',30);

