function plot_full_synthetic_catchwords_v2(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 01-Mar-2015 11:58:46

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontWeight','bold','FontSize',30);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

cl = distinguishable_colors(6);
% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'MarkerSize',10,'LineWidth',4);
set(plot1(1),'Marker','+','Color',cl(1,:),'DisplayName','Heur-SPA');
set(plot1(2),'Marker','o','Color',cl(2,:),'DisplayName','SPA');
set(plot1(3),'Marker','square','Color',cl(3,:),'DisplayName','XRAY');
set(plot1(4),'Marker','d','Color',cl(4,:),'DisplayName','ER-SPA');
set(plot1(5),'Marker','*','Color',cl(5,:),'DisplayName','ER-XRAY');

set(plot1(6),'Marker','<','Color',cl(6,:),'DisplayName','UTSVD');

% Create xlabel
xlabel('Noise level ($\beta$)','Interpreter','latex','FontWeight','bold',...
    'FontSize',40);

% Create ylabel
ylabel('1-normalized $\ell_s$ Residual norm','Interpreter','latex','FontWeight','bold',...
    'FontSize',40);

% Create title
title('Synthetic catchwords',...
    'Interpreter','latex',...
    'FontWeight','bold',...
    'FontSize',45);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.723261032161556 0.62107904642409 0.177823485415107 0.295169385194475],...
    'FontSize',30);

