function plot_full_synthetic_separable(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 27-Feb-2015 14:53:45

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontWeight','bold','FontSize',16);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'MarkerSize',8,'LineWidth',2);
set(plot1(1),'Marker','+','Color',[0 1 0],'DisplayName','Heur-SPA');
% set(plot1(2),'Marker','o','Color',[0 0 1],'DisplayName','PostPrecSPA');
% set(plot1(3),'Marker','square','Color',[0 1 1],'DisplayName','HottTopixx');
set(plot1(2),'Marker','o','Color',[1 0 0],'DisplayName','SPA');
set(plot1(3),'LineStyle','--','Color',[0 1 0],'DisplayName','XRAY');
set(plot1(4),'Marker','x','Color',[0 0 0],'DisplayName','ER-SPA');
set(plot1(5),'Marker','square','Color',[0 1 1],'DisplayName','ER-XRAY');

% set(plot1(6),'Marker','+','DisplayName','LP-rho1','Color',[0 0 0]);
set(plot1(6),'Marker','diamond','Color',[1 0 0],'DisplayName','true-K');
set(plot1(7),'Marker','<','Color',[1 0 1],'DisplayName','UTSVD');

% Create xlabel
xlabel('Noise level ($\delta$)','Interpreter','latex','FontWeight','bold',...
    'FontSize',24);

% Create ylabel
ylabel('$\ell_{s}$ Residual norm','Interpreter','latex','FontWeight','bold',...
    'FontSize',24);

% Create title
title('Synthetic separable: $\ell_{s}$ Residual norm of $A$',...
    'Interpreter','latex',...
    'FontWeight','bold',...
    'FontSize',30);

% Create legend
legend1 = legend(axes1,'show');
% set(legend1,...
%     'Position',[0.694152923538231 0.524466750313676 0.206709145427285 0.391781681304889],...
%     'FontSize',20);
set(legend1,...
    'Location','northeast',...
    'FontSize',20);


